### PR TITLE
Fix/83 python37

### LINKED ISSUE #83: pyamtrack doesn't work on python 3.7
```
(pyamtrack1) grzanka@grzanka-VirtualBox:~$ pip install pyamtrack
Collecting pyamtrack
  Downloading https://files.pythonhosted.org/packages/27/ad/2c0e74c8b53fe8aa1e2c87b4002fb6b816bf83541c384c9c45551c7cdf3a/pyamtrack-0.1.1-py3-none-manylinux1_x86_64.whl (4.8MB)
     |████████████████████████████████| 4.8MB 1.1MB/s 
Collecting cffi>=1.13.0
  Downloading https://files.pythonhosted.org/packages/16/cd/1f4ddf6be8300713c676bb9f3a2d3b8eb8accc0a6a24f57d4f6c4cd59d34/cffi-1.13.2-cp37-cp37m-manylinux1_x86_64.whl (398kB)
     |████████████████████████████████| 399kB 53.8MB/s 
Processing ./.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511/pycparser-2.19-py2.py3-none-any.whl
Installing collected packages: pycparser, cffi, pyamtrack
Successfully installed cffi-1.13.2 pyamtrack-0.1.1 pycparser-2.19
(pyamtrack1) grzanka@grzanka-VirtualBox:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyamtrack import libAT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grzanka/.conda/envs/pyamtrack1/lib/python3.7/site-packages/pyamtrack/libAT.py", line 2, in <module>
    from .lib import _libAT
ImportError: cannot import name '_libAT' from 'pyamtrack.lib' (/home/grzanka/.conda/envs/pyamtrack1/lib/python3.7/site-packages/pyamtrack/lib/__init__.py)
>>> 
(pyamtrack1) grzanka@grzanka-VirtualBox:~$ python -V
Python 3.7.6

```

tested with Anaconda

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #83

### CODE REVIEW

**Comment by grzanka** [comment]
Still needs to merge https://github.com/Tetrite/cBinder/pull/82
